#!/bin/bash
SUFFIX="-"

if [ ! -f $2$SUFFIX ];
then
  mv $1 $2$SUFFIX
else
  SUFFIX="="
  if [ ! -f $2$SUFFIX ];
  then
    mv $1 $2$SUFFIX
  else
    echo "Could not switch files; both $2- and $2= exist :/"
    exit 1
  fi
fi
mv $2 $1
mv $2$SUFFIX $2
